# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-01 16:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170128_1123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={'ordering': ('-date',), 'verbose_name': 'Blog page', 'verbose_name_plural': 'Blog pages'},
        ),
        migrations.AddField(
            model_name='blogpage',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.today, help_text='This date may be displayed on the blog post. It is not used to schedule posts to go live at a later date.', verbose_name='Post date'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='content',
            field=wagtail.wagtailcore.fields.StreamField((('text', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('title', wagtail.wagtailcore.blocks.CharBlock(required=False))))), ('brightcove_video', wagtail.wagtailcore.blocks.URLBlock(template='blocks/brightcove_video.html')), ('embed', wagtail.wagtailembeds.blocks.EmbedBlock()), ('columns', wagtail.wagtailcore.blocks.StreamBlock((('image', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('title', wagtail.wagtailcore.blocks.CharBlock(required=False))), template='blocks/column_image.html')), ('text', wagtail.wagtailcore.blocks.RichTextBlock())))), ('large_columns', wagtail.wagtailcore.blocks.StreamBlock((('text', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('title', wagtail.wagtailcore.blocks.CharBlock(required=False)))))))), ('image_and_text', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('image_title', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('image_position', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right')])), ('text', wagtail.wagtailcore.blocks.RichTextBlock())), template='blocks/image_and_text.html')), ('gallery', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('title', wagtail.wagtailcore.blocks.CharBlock(required=False)))), template='blocks/gallery.html'))), blank=True, null=True),
        ),
    ]
