# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-01 16:51
from __future__ import unicode_literals
from datetime import datetime
import pytz

from django.db import migrations


def forwards_func(apps, schema_editor):
    BlogPage = apps.get_model("blog", "BlogPage")
    db_alias = schema_editor.connection.alias

    for b in BlogPage.objects.using(db_alias).all():
        d = datetime(b.date.year, b.date.month, b.date.day, 0, 0, 0, tzinfo=pytz.timezone('EST'))
        b.date_time = d
        b.save()

def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170201_1151'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
