# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-01 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170201_1151'),
    ]

    operations = [
        migrations.RemoveField('blogpage', 'date'),
        migrations.RenameField('blogpage', 'date_time', 'date')
    ]
